server.port=8080
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.web.resources.add-mappings=false

spring.datasource.url=jdbc:h2:file:./target/roomly-local-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

supabase.url=${SUPABASE_PROJECT_URL:https://klhgcqoypnxkqnrnbesz.supabase.co}
supabase.api-key=${SUPABASE_API_KEY:}
supabase.storage.api-key=${SUPABASE_STORAGE_API_KEY:${SUPABASE_API_KEY:}}
supabase.storage.bucket-name=${SUPABASE_STORAGE_BUCKET:roomly-images}
supabase.jwt-secret=${JWT_SECRET:}